### ISSUE TITLE
OKD: Check time zones, especially on YCC Hull server

### ISSUE THREAD

**Issue by LajosCseppento** [Yachting-Club-CERN/ycc-infra#18]
Critical, as latter uses `now()`

Maybe this is enough:

```yaml
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: TZ
      value: Europe/Zurich
```
